### ISSUE TITLE
USER STORY: Navigate between rooms 

### ISSUE THREAD

**Issue by nils-n** [nils-n/boo-army#14]
As a **website user** I can **interact with elements on the website such as buttons for multiple choice options* so that ** I can trigger an action such as navigate to the next room or peform an action to ensure my survival in the game**

## Tasks:
- [ ] Design all multiple choices for each room
- [ ] Define each transition between rooms
- [ ] Animate each room and response to each of the choices
